### ISSUE TITLE
DEPRECATION: Overriding init without calling this._super is deprecated.

### ISSUE THREAD

**Issue by notmessenger** [kpfefferle/ember-cli-deploy-cloudfront#14]
Received when running `ember serve` in Ember CLI version 2.6.1

```
DEPRECATION: Overriding init without calling this._super is deprecated. Please call this._super()
    at Object.<anonymous> (/Users/Documents/my-project/node_modules/ember-cli-deploy-cloudfront/lib/cloudfront.js:7:29)
```

**Comment by kpfefferle** [comment]
Thanks for the report!

Have you updated to the latest 0.2.8 release? I believe that this deprecation was addressed in https://github.com/kpfefferle/ember-cli-deploy-cloudfront/commit/9d5beedf1d3537f6415e3ba80de4f502f75a9dde

**Comment by notmessenger** [comment]
After upgrading to the 0.2.8 release this deprecation went away.  Thanks and sorry about that!

**Comment by kpfefferle** [comment]
@notmessenger Thanks for reporting back that the update indeed fixed the warning for you! 👍
