### ISSUE TITLE
Disable invalidation when deploying to staging

### ISSUE THREAD

**Issue by taylon** [kpfefferle/ember-cli-deploy-cloudfront#3]
Hi,

I need to disable this plugin when deploying to staging. I've been doing it by setting `activateOnDeploy` to false when `deployTarget` is staging.

Do you think it is the best way of doing it? Or maybe it would be better to provide a clear option for this in the plugin? 

Let me know if you think something should be implemented in the plugin and I'll do it =D

**Comment by kpfefferle** [comment]
I think you're on the right track. If you're wanting to automatically run the activation hooks only on production (and not on staging or elsewhere), I'd simply set `activateOnDeploy` conditionally based on the environment:

```javascript
activateOnDeploy: deployTarget === 'production'
```

**Comment by taylon** [comment]
Nice, I added that to the README file in a pull request to make it easier for other users =D
