### ISSUE TITLE
AWS Cloudfront configuration

### ISSUE THREAD

**Issue by woosungchu** [kpfefferle/ember-cli-deploy-cloudfront#46]
Similar issue with #5

AWS cloudfront require more option than current configuration in README.md
```
Error
Missing required field Principal
```
And I tried to add required options but..
```
Error
Policy has invalid action...
Policy has invalid resource...
```

**Comment by woosungchu** [comment]
And this works....
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": "s3:GetObject",
      "Principal": "*",      
      "Resource": "arn:aws:s3:::[your-bucket-name]/*"
    }
  ]
}
```

**Comment by kpfefferle** [comment]
@woosungchu What issue were you experiencing that required these additional permissions? The permissions that we've listed in the README are specifically tailored around what's needed in order for the executing user to perform a CloudFront invalidation. The permissions you've listed related to S3 wouldn't seem to have anything to do with the actions that this particular plugin are performing. Is there something more I'm missing?

**Comment by woosungchu** [comment]
@kpfefferle 
As I am new in AWS cloudfront, I just tried to copy and patse README.md configuration but they were not working. So I thought there was some change in AWS minimum configuration. If I get wrong and everything is fine, I am sorry to bother you. 

*Thank you to maintain this good open source
