### ISSUE TITLE
Required permissions for AWS

### ISSUE THREAD

**Issue by ryanto** [kpfefferle/ember-cli-deploy-cloudfront#5]
Is there a recommended minimum permission to use this addon? I think it might be worth adding to the readme. Here's an example of `ember-cli-deploy-s3` permissions https://github.com/ember-cli-deploy/ember-cli-deploy-s3#minimum-s3-permissions

Btw, thanks so much for the amazing deploy addon! We're loving it.

**Comment by ryanto** [comment]
It looks like you cannot use IAM to control access to a specific cloud front distribution. What do you this of recommending this permission? I can PR into `README.md` if you're ok with it.

```
{
   "Version": "2012-10-17",
   "Statement":[{
      "Effect":"Allow",
      "Action":["cloudfront:*"],
      "Resource":"*"
      }
   ]
}
```

http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/UsingWithIAM.html

**Comment by kpfefferle** [comment]
@ryanto: It looks like the only restriction that could be placed on the IAM access would be to limit access to only the `CreateInvalidation` action, but I'm not sure being this specific is really necessary for the typical use case (seeing as we can't limit to specific distributions).

```
{
   "Version": "2012-10-17",
   "Statement":[{
      "Effect":"Allow",
      "Action":["cloudfront:CreateInvalidation"],
      "Resource":"*"
      }
   ]
}
```

I'm fine with adding the more general IAM permission that you suggested to the README. The example you gave from ember-cli-deploy-s3 looks good for formatting.
