### ISSUE TITLE
Support using profile defined in ~/.aws/credentials

### ISSUE THREAD

**Issue by eduardoweiland** [kpfefferle/ember-cli-deploy-cloudfront#57]
The `profile` option is provided in [ember-cli-deploy-s3](https://github.com/ember-cli-deploy/ember-cli-deploy-s3#profile) and I find it really useful. I think it will be good to have this option in this plugin too, so both plugins can be configured in the same way.

**Comment by kpfefferle** [comment]
@eduardoweiland This has been released in [v1.2.0](https://github.com/kpfefferle/ember-cli-deploy-cloudfront/releases/tag/v1.2.0) thanks to @jhliberty!
