### ISSUE TITLE
More configurable `objectPaths`

### ISSUE THREAD

**Issue by xcambar** [kpfefferle/ember-cli-deploy-cloudfront#67]
[adapted from Slack]

Hi!
I'd like to discuss alternatives for an enhancement to `ember-cli-deploy-cloudfront`. Here they are:

## rationale

We'd like the ability to dynamically select a file, based on the revision data.

So instead of `objectPaths: ['vendor/locales/en.json']`, we'd like to have some sort of `['vendor/locales/MY_REVISION_HASH/en.json']`

## Proposal

Here are the 2 alternatives we have thought of so far:

* use a **template-like string replacement**: `objectPaths: ['vendor/locales/{revision.hash}/en.json']` and the plugin with do the rest
* use a **function as `objectPaths`**, as in
```
objectPaths: function(context) {
  // Do the thing
  return whateverArrayHasBeenBuilt;
}
```

Of course, both solutions MUST be backward compatible

Which one do you think is best suited?
Do you see an alternative?
I'll get to it after I've read your initial feedback about the above.

**Comment by kpfefferle** [comment]
I'm thinking I might personally prefer Option 2 (the `function` syntax). While Option 1 provides a slick, simple API, my guess is it would require a bit more "magic" within the plugin and be less flexible to other potential future dynamic uses.

Implementation for Option 2 not only wouldn't tie us to a specific string-interpolation format, but might be simpler to implement. If `objectPaths` is an array of strings, then use them as we always have, else if `objectPaths` is a `function`, then evaluate and use the array of strings it returns 👍🏻
