### ISSUE TITLE
Only run if ENV.cloudfront exists

### ISSUE THREAD

**Issue by urbany** [kpfefferle/ember-cli-deploy-cloudfront#8]
Hi, first of all thanks for the plugin!

I'm trying to deploy and activate an environment without running this plugin but seems like there is no way to do that right now.

Can you consider adding something here that checks if ENV.cloudfront is set and if not it doesn't try to invalidate? https://github.com/kpfefferle/ember-cli-deploy-cloudfront/blob/master/index.js#L29

Right now I'm getting: ``- Missing required config: `distribution``` so maybe if it doesn't exist just return instead?

**Comment by kpfefferle** [comment]
Hi @urbany! Can you help me understand your use case a bit better? Are you using CloudFront in some environments (like production) and not others (like staging), but you're using an activation strategy in both environments?

I can see why this is something we'd want to support. I just want to make sure I understand the use case accurately before considering possible approaches to solving the problem.

Thanks!

**Comment by urbany** [comment]
Hi Kevin, thanks for the quick reply. Yes that is entirely correct. Let me
know if I can help with anything else.

Hi @urbany <https://github.com/urbany>! Can you help me understand your use
case a bit better? Are you using CloudFront in some environments (like
production) and not others (like staging), but you're using an activation
strategy in both environments?

I can see why this is something we'd want to support. I just want to make
sure I understand the use case accurately before considering possible
approaches to solving the problem.

Thanks!

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/kpfefferle/ember-cli-deploy-cloudfront/issues/8#issuecomment-210702160>

**Comment by urbany** [comment]
Hi @kpfefferle did you get any time to check this? Any way I can help?

**Comment by kpfefferle** [comment]
@urbany I've been looking into how this is handled elsewhere in the ember-cli-deploy ecosystem. I wanted to make sure that anything the CloudFront plugin implements is consistent with other plugins.

The good news is that ember-cli-deploy is working on per-plugin disabling as a core feature: https://github.com/ember-cli-deploy/ember-cli-deploy/pull/349
The bad news is that PR hasn't been landed yet, but when it's done it will be easy to disable the CloudFront plugin:

```
ENV.cloudfront.disabled = true
```

I do want to provide a workaround in the meantime. There is a method of whitelisting only certain plugins to execute in a particular environment. This is used in the ember-cli-deploy-lightning-pack sample config seen here: https://github.com/ember-cli-deploy/ember-cli-deploy-lightning-pack/blob/master/blueprints/lightning-deploy-config/files/config/deploy.js#L25
For someone using the ember-cli-deploy-aws-pack for example, the whitelist could include everything *except* CloudFront in a particular environment:

```
ENV.plugins = ['build', 'gzip', 's3', 'manifest'];
```

While a whitelist could grow unwieldy for complicated deploys, I think it's acceptable as a temporary workaround until the per-plugin `disabled` syntax (which is pretty ideal) is available in the core of ember-cli-deploy. I don't think it makes sense to add plugin-specific logic to this CloudFront plugin given the above.

**Comment by kpfefferle** [comment]
I added this information to the README also: https://github.com/kpfefferle/ember-cli-deploy-cloudfront/commit/ac6229e97bf26d5f2c848ca7a8ef25e66b25a322
